<?php
$typeArr[1] = '技术资源';
$typeArr[2] = '技术工具';
$typeArr[3] = '资源下载';
$typeArr[4] = '主机域名';
$typeArr[5] = '游戏软件';
$typeArr[6] = '博客大全';
$typeArr[7] = '休闲娱乐';
$typeArr[8] = '影视音乐';
$typeArr[9] = '小说阅读';
$typeArr[10] = '美文娱乐';
$typeArr[11] = '新闻资讯';
$typeArr[12] = '企业门户';
$typeArr[13] = '公司企业';
$typeArr[14] = '政府单位';
$typeArr[15] = '地方门户';
$typeArr[16] = '人才招聘';
$typeArr[17] = '教育培训';
$typeArr[18] = '垂直行业';
$typeArr[19] = '站长之家';
$typeArr[20] = '站长论坛';
$typeArr[21] = 'seo优化';
$typeArr[22] = '投稿';
?>