<div class="col-xs-6 col-sm-4 col-md-3">
          <div class="item"> <a class="link" target="_blank" href="http://[field:arcurl/]" rel="nofollow"><i class="autoleft fa fa-angle-right" title="直达网站"></i></a> <a class="a" href="[field:arcurl/]" title="[field:title /]" target="_blank"> <img class="img-cover br" src="[field:litpic /]" alt="[field:title /]" title="[field:title /]">
            <h3>[field:title /]</h3>
            <p> [field:description function='cn_substr(@me,100)'/]...</p>
            </a> </div>
        </div>