<?php
$z[0]=Array("field","",54,82);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",84,113);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n              <li id=\"navbar-category-8\" class=\"li-cate-8\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n              ",168,352);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>