<?php
$z[0]=Array("field","",42,71);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",113,142);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",168,197);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",205,233);
$z[3][4]=array();
$z[3][4]['name']="typeurl";
$z[4]=Array("arclist","\r\n            <div class=\"col-xs-6 col-sm-4 col-md-3\">\r\n              <div class=\"item art-item transition\"> <a class=\"art-a\" href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\"> <img class=\"img-cover\" src=\"[field:litpic/]\" alt=\"[field:title/]\" title=\"[field:title/]\"> </a>\r\n                <h3 class=\"art-title\"><a class=\"\" href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:title/]</a></h3>\r\n                <p>[field:description function='cn_substr(@me,100)'/]...</p>\r\n              </div>\r\n            </div>\r\n            ",323,928);
$z[4][4]=array();
$z[4][4]['row']="8";
$z[4][4]['titlelen']="60";

?>