<?php
$z[0]=Array("top","\r\n    <m:item name='模块管理' link='module_main.php' rank='sys_module' target='main' />\r\n    <m:item name='上传新模块' link='module_upload.php' rank='sys_module' target='main' />\r\n    <m:item name='模块生成向导' link='module_make.php' rank='sys_module' target='main' />\r\n    ",51,399);
$z[0][4]=array();
$z[0][4]['name']="模块管理";
$z[0][4]['c']="6,";
$z[0][4]['display']="block";
$z[1]=Array("top","\r\n  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />\r\n  <m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />\r\n\r\n",401,653);
$z[1][4]=array();
$z[1][4]['item']="7";
$z[1][4]['name']="辅助插件";
$z[1][4]['display']="block";

?>