
<field:biaoti itemname="网站标题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:biaoti>

<field:tubiao itemname="网站图标" autofield="1" type="img" isnull="true" default=""  maxlength="250" page="">
</field:tubiao>

<field:wangzhi itemname="网址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:wangzhi>

<field:jianjie itemname="网站简介" autofield="1" type="htmltext" isnull="true" default=""  maxlength="250" page="">
</field:jianjie>

<field:liuyanshijian itemname="投稿时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:liuyanshijian>
