<?php
$z[0]=Array("field","",41,70);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",112,141);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",167,196);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",204,232);
$z[3][4]=array();
$z[3][4]['name']="typeurl";
$z[4]=Array("arclist","\r\n            <div class=\"col-xs-6 col-sm-4 col-md-3\">\r\n              <div class=\"item\"> <a class=\"link\" target=\"_blank\" href=\"http://[field:link/]\" rel=\"nofollow\"><i class=\"autoleft fa fa-angle-right\" title=\"直达网站\"></i></a> <a class=\"a\" href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\"> <img src=\"[field:litpic/]\" alt=\"[field:title/]\" title=\"[field:title/]\">\r\n                <h3>[field:title/]</h3>\r\n                <p>[field:description function='cn_substr(@me,100)'/]...</p>\r\n                </a> </div>\r\n            </div>\r\n            ",322,951);
$z[4][4]=array();
$z[4][4]['row']="8";
$z[4][4]['titlelen']="60";
$z[4][4]['addfields']="link";

?>