<?php
$z[0]=Array("global","",159,180);
$z[0][4]=array();
$z[0][4]['name']="cfg_qq";
$z[1]=Array("global","",276,300);
$z[1][4]=array();
$z[1][4]['name']="cfg_beian";
$z[2]=Array("global","",392,418);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",427,453);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",527,553);
$z[4][4]=array();
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",562,588);
$z[5][4]=array();
$z[5][4]['name']="cfg_webname";
$z[6]=Array("type","<a id=\"quick_submit\" class=\"fa fa-pencil\" rel=\"nofollow\" href=\"[field:typelink /]\"></a>",633,755);
$z[6][4]=array();
$z[6][4]['typeid']="22";

?>